#!/bin/bash

echo "Committing as: $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>"

if [[ ("`pwd`" == "$HOME/dev"*) && "$GIT_AUTHOR_EMAIL" == *gmail* ]]; then
    echo Error: Email not set correctly
    exit 1
fi
