# Path to your oh-my-zsh installation.
export ZSH=$HOME/dotfiles/oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="frisk"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(aws)
SHOW_AWS_PROMPT=false

# User configuration
# for bash completion script support
autoload -U +X bashcompinit && bashcompinit

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin"
#source /etc/environment
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh
source $HOME/dotfiles/zsh/aliases

unsetopt beep

# To prevent % after every command in conemu. see: http://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows
#setopt PROMPT_CR
#setopt PROMPT_SP
export PROMPT_EOL_MARK=""

# for colored output of 'tree'
eval "$(dircolors)"
export LS_COLORS="$LS_COLORS:ow=34;100:"

# navigation
autoload -U select-word-style
export WORDCHARS="~%^&\$*(){}[]<>?.+;-_'\""
select-word-style normal

backward-shell() { zle backward-word }
forward-shell() { zle forward-word }
backward-kill-shell() { zle backward-kill-word }
zle -N backward-shell
zle -N forward-shell
zle -N backward-kill-shell
zstyle ':zle:*-shell' word-style shell

bindkey '^[[1;3D' backward-shell  # alt+left
bindkey '^[[1;3C' forward-shell  # alt+right
bindkey '^F' backward-kill-shell
bindkey '^U' backward-kill-line

# https://github.com/junegunn/fzf
# command-line fuzzy finder
source ~/dotfiles/fzf/shell/completion.zsh
source ~/dotfiles/fzf/shell/key-bindings.zsh

to_source=(
    # in order to keep the current working directory when opening a new terminal tab in gnome
    /etc/profile.d/vte.sh
    # gsutil command completion
    /usr/share/google-cloud-sdk/completion.zsh.inc
    /usr/share/bash-completion/completions/task.bash
    ~/miniconda3/etc/profile.d/conda.sh
    /opt/miniconda3/etc/profile.d/conda.sh
    ~/.config/broot/launcher/bash/br
    # on ubuntu
    /etc/profile.d/autojump.zsh
    # on archlinux
    /usr/share/autojump/autojump.zsh
    /usr/share/nvm/init-nvm.sh
)
for file in "${to_source[@]}"; do
    if [[ -e "$file" ]]; then
        source "$file"
    fi
done


# snakemake command completion
compdef _gnu_generic snakemake

[[ $commands[kubectl] ]] && source <(kubectl completion zsh) && compdef k=kubectl
[[ $commands[helm] ]] && source <(helm completion zsh)
[[ $commands[eksctl] ]] && source <(eksctl completion zsh)


# aliases for quickly editing zshrc etc
function reload() { source ~/.zshrc; source ~/.zshenv; }
alias ec='$EDITOR ~/dotfiles/zsh/zshrc && reload'
alias ea='$EDITOR ~/dotfiles/zsh/aliases && reload'
alias ee='$EDITOR ~/dotfiles/zsh/zshenv && reload'
alias eel='$EDITOR ~/.zshenv-local && reload'


