# Path to your oh-my-zsh installation.
export ZSH=$HOME/dotfiles/oh-my-zsh
export ZSH_CUSTOM=$HOME/dotfiles/zsh/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="frisk"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-syntax-highlighting)

# User configuration
# for bash completion script support
autoload -U +X bashcompinit && bashcompinit

export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/dotfiles/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh
source $HOME/dotfiles/zsh/aliases

# in order to keep the current working directory when opening a new terminal tab in gnome
if [[ -e /etc/profile.d/vte.sh ]]; then
    source /etc/profile.d/vte.sh
fi

export EDITOR='vim'

unsetopt beep

# To prevent % after every command in conemu. see: http://superuser.com/questions/645599/why-is-a-percent-sign-appearing-before-each-prompt-on-zsh-in-windows
#setopt PROMPT_CR
#setopt PROMPT_SP
export PROMPT_EOL_MARK=""

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# on archlinux
if [[ -e /etc/profile.d/autojump.zsh ]]; then
    source /etc/profile.d/autojump.zsh
fi
# on ubuntu
if [[ -e /usr/share/autojump/autojump.zsh ]]; then
    source /usr/share/autojump/autojump.zsh
fi

# for colored output of 'tree'
eval "$(dircolors)"

bindkey '^U' backward-kill-line

# https://github.com/junegunn/fzf
# command-line fuzzy finder
source ~/dotfiles/fzf/shell/completion.zsh
source ~/dotfiles/fzf/shell/key-bindings.zsh

# gsutil command completion
if [[ -e /usr/share/autojump/autojump.zsh ]]; then
    source /usr/share/google-cloud-sdk/completion.zsh.inc
fi

# snakemake command completion
#if type snakemake &> /dev/null; then
#    $(snakemake --bash-completion)
#fi

if [[ -e ~/miniconda3/etc/profile.d/conda.sh ]]; then
    source ~/miniconda3/etc/profile.d/conda.sh
fi

